#' Creates a \code{NWBHDF5IO} file container
#' @examples
#' \dontrun{
#'
#' # Running this example requires a .nwb file
#'
#' library(rnwb)
#' container <- NWBHDF5IO$new(path = file)
#' container$with({
#'
#'   data <- container$read()
#'   electrode_table <- data$electrodes[convert = TRUE]
#'
#' })
#'
#' print(electrode_table)
#'
#' }
#' @export
NWBHDF5IO <- R6::R6Class(
  classname = "NWBHDF5IO",
  portable = FALSE,
  cloneable = FALSE,
  private = list(
    construct_params = NULL,
    .file_handler = NULL,
    ensure_file_handler = function() {
      # check if .file_handler is valid
      ptr <- private$.file_handler
      if(is.null(ptr) || is_invalid_pointer(ptr)) {
        nwb <- load_nwb()
        ptr <- do.call(nwb$NWBHDF5IO, private$construct_params)
        private$.file_handler <- ptr
      }
      return(ptr)
    },
    finalize = function(...) {
      self$close()
    }
  ),
  public = list(
    #' @description
    #' Initialize the class
    #' @param path Path to a \code{'.nwb'} file
    #' @param mode Mode for opening the file
    #' @param ... Other parameters passed to \code{nwb$NWBHDF5IO}
    initialize = function(
      path = NULL, mode = c("r", "w", "r+", "a", "w-", "x"), ...) {
      if(length(path)) {
        path <- normalizePath(path)
      }
      mode <- match.arg(mode)
      private$construct_params <- list(
        path = path, mode = mode, ...
      )
    },

    #' @description
    #' Close the connections (low-level method, see 'with' method below)
    #' @param close_links Whether to close all files linked to from this
    #' file; default is true
    #' @returns Nothing
    close = function(close_links = TRUE) {
      ptr <- private$.file_handler
      if(is.null(ptr) || is_invalid_pointer(ptr)) { return(invisible()) }
      # clean up and close the file handler
      verbose_debug("Closing the [NWBHDF5IO] file handler")
      tryCatch({
        ptr$close(close_links = as.logical(close_links))
      }, error = warning)
      # important: remove the pointer or segfault
      private$.file_handler <- NULL
      invisible()
    },

    #' @description
    #' Close all opened, linked-to files. 'MacOS' and 'Linux' automatically
    #' release the linked-to file after the linking file is closed, but
    #' 'Windows' does not, which prevents the linked-to file from being
    #' deleted or truncated. Use this method to close all opened,
    #' linked-to files.
    #' @returns Nothing
    close_linked_files = function() {
      ptr <- private$.file_handler
      if(is.null(ptr) || is_invalid_pointer(ptr)) { return(invisible()) }
      # clean up and close the file handler
      verbose_debug("Closing the [NWBHDF5IO] all linked files")
      tryCatch({
        ptr$close_linked_files()
      }, error = warning)
      # important: remove the pointer or segfault
      private$.file_handler <- NULL
      invisible()
    },

    #' @description
    #' Read the 'NWB' file from the 'IO' source. Please use along with
    #' \code{'$with'} method
    #' @returns \code{'NWBFile'} container
    read = function() {
      if(!self$opened) {
        stop("The file is not opened. Must run under x$with context")
      }
      handler <- private$ensure_file_handler()
      return(handler$read())
    },

    #' @description
    #' Safe wrapper for reading and handling 'NWB' file. See class examples.
    #' @param expr R expression to evaluate
    #' @param quoted Whether \code{expr} is quoted; default is false
    #' @param envir environment for \code{expr} to evaluate; default is the
    #' parent frame (see \code{parent.frame})
    #' @returns Whatever results generated by \code{expr}
    with = function(expr, quoted = FALSE, envir = parent.frame()) {
      if(!quoted) {
        expr <- substitute(expr)
      }
      private$ensure_file_handler()
      # Make sure closing the file links when exiting the function
      on.exit({ self$close() })
      if(!self$opened) {
        stop("Cannot open file...")
      }
      eval(expr, envir = envir)
    }
  ),
  active = list(

    #' @field opened Whether the container is opened.
    opened = function() {
      ptr <- private$.file_handler
      if(is.null(ptr) || is_invalid_pointer(ptr)) {
        return(FALSE)
      }
      return(TRUE)
    }
  )
)
